# Generated by Django 4.1.1 on 2022-10-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_site', models.ImageField(upload_to='logo_site/')),
                ('name_site', models.CharField(max_length=255)),
                ('descriptions_site', models.CharField(max_length=255)),
                ('numder_site', models.CharField(max_length=255)),
                ('twitter_site', models.URLField()),
                ('facebook_site', models.URLField()),
                ('instagram_site', models.URLField()),
                ('tiktok_site', models.URLField()),
                ('youtube_site', models.URLField()),
            ],
        ),
    ]
