# Generated by Django 4.1.1 on 2022-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_numder_site_settings_number_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_s', models.ImageField(upload_to='logo_site/')),
                ('about_s', models.CharField(max_length=255)),
                ('desc_s', models.CharField(max_length=255)),
                ('photo_1', models.ImageField(upload_to='photo_s/')),
                ('about_1', models.CharField(max_length=255)),
                ('desc_1', models.CharField(max_length=255)),
                ('photo_2', models.ImageField(upload_to='photo_s/')),
                ('about_2', models.CharField(max_length=255)),
                ('desc_2', models.CharField(max_length=255)),
                ('photo_3', models.ImageField(upload_to='photo_s/')),
                ('about_3', models.CharField(max_length=255)),
                ('desc_3', models.CharField(max_length=255)),
            ],
        ),
    ]
