# Generated by Django 4.1.1 on 2022-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_info_photo_1_remove_info_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройка'},
        ),
        migrations.AddField(
            model_name='info',
            name='dop_desc_1',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_desc_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_desc_3',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_name_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_name_2',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_name_3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_photo_1',
            field=models.ImageField(default=1, upload_to='logo_site/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_photo_2',
            field=models.ImageField(default=1, upload_to='logo_site/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='dop_photo_3',
            field=models.ImageField(default=1, upload_to='logo_site/'),
            preserve_default=False,
        ),
    ]
