# Generated by Django 4.1.1 on 2022-10-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_con1',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email_con2',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
