# Generated by Django 4.1.1 on 2022-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_contact_email_con1_contact_email_con2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_photo1', models.ImageField(upload_to='', verbose_name='slide_photo/')),
                ('slide_name1', models.CharField(max_length=255)),
                ('slide_desc1', models.CharField(max_length=255)),
                ('slide_photo2', models.ImageField(upload_to='', verbose_name='slide_photo/')),
                ('slide_name2', models.CharField(max_length=255)),
                ('slide_desc2', models.CharField(max_length=255)),
                ('slide_photo3', models.ImageField(upload_to='', verbose_name='slide_photo/')),
                ('slide_name3', models.CharField(max_length=255)),
                ('slide_desc3', models.CharField(max_length=255)),
            ],
        ),
    ]
