# Generated by Django 4.1.1 on 2022-10-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайды', 'verbose_name_plural': 'Слайд'},
        ),
    ]
