# Generated by Django 4.1.1 on 2022-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_slide_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_photo', models.ImageField(upload_to='', verbose_name='product_photo/')),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_price', models.CharField(max_length=255)),
                ('pro_price_rebate', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукт',
            },
        ),
    ]
