# Generated by Django 4.1.1 on 2022-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_products_pro_desc_products_pro_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_photo2',
            field=models.ImageField(default=0, upload_to='', verbose_name='product_photo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pro_photo3',
            field=models.ImageField(default=0, upload_to='', verbose_name='product_photo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pro_photo4',
            field=models.ImageField(default=0, upload_to='', verbose_name='product_photo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pro_photo5',
            field=models.ImageField(default=0, upload_to='', verbose_name='product_photo/'),
            preserve_default=False,
        ),
    ]
