# Generated by Django 4.1.1 on 2022-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email_con1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='location_site',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number_1',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number_2',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_con2',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='email_con2',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='location_site',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone_number_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
