# Generated by Django 4.1.1 on 2022-10-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_delete_contacts_rename_email_con1_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='email_con2',
            new_name='email_site',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone_number_2',
        ),
    ]
