# Generated by Django 4.1.1 on 2022-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='money',
            name='name2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='name3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='name4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='name5',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
