# Generated by Django 4.1.1 on 2022-10-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_rename_name_money_name1_money_name2_money_name3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='Kazahstan',
            new_name='kazahstan',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='Kyrgyzstan',
            new_name='kyrgyzstan',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='Russia',
            new_name='russia',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='USA',
            new_name='usa',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='Uzbekiston',
            new_name='uzbekiston',
        ),
    ]
